### ISSUE TITLE
Issues after installing the pathc?

### ISSUE THREAD

**Issue by lAlexl7l** [leecher1337/flashpatch#3]
So i have an old screensaver that uses Active X i reinstall windows and use this feature to be able to allow it but then i get this error when i open the setting for it
https://files.catbox.moe/8jgm9v.png
any idea waht could cause it?

**Comment by leecher1337** [comment]
Maybe you're facting this issue:
https://stackoverflow.com/questions/8200581/twebbrowser-crashes-with-embedded-youtube-clips

My guess is that your Screensaver is using a Delphi starter app that uses an embedded Webbrowser control which in turn is facing an FPU exception.
Maybe you need to patch the startup program to mask FPU exceptions. For further analysis and possibly patching, I would need to get hold of the screensaver. Maybe via e-mail?

**Comment by lAlexl7l** [comment]
Here is the screensaver
https://files.catbox.moe/cf8ebs.rar

**Comment by leecher1337** [comment]
Shuold work now with latest patch, please check

**Comment by lAlexl7l** [comment]
It now works thanks for the solution
